import type { Metadata } from "next";
import Link from 'next/link'
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}


const buttonStyle = "px-4 py-2 rounded hover:bg-blue-700 transition duration-200";

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex flex-col min-h-screen">

      {/* Navbar */}
      <nav className="bg-blue-900 p-4">
        <div className="container mx-auto flex items-center justify-between font-bold text-white">
          <div className="flex items-center space-x-5">
            <Image
              src="/images/logo.png"
              alt="Basketball Court Logo"
              width={50}
              height={50}
              className="object-contain transform transition-transform duration-300 hover:rotate-180"          
            />
            <Link href="/" className={buttonStyle}>Home</Link>
            <Link href="/reservations" className={buttonStyle}>Reservations</Link>
            <Link href="/contact" className={buttonStyle}>Contact</Link>
            <Link href="/about" className={buttonStyle}>About</Link>
          </div>
          <Link href="/" className={buttonStyle}>Log in</Link>
        </div>
      </nav>


      {/* Main Content */}
      <main className="flex-grow">
        {children}
      </main>

      {/* Footer */}
      <footer className="bg-blue-900 text-white py-5">
        <div className="container mx-auto px-4 text-center">
          <p>&copy; {new Date().getFullYear()} bookyourcourt.com - Strona na zaliczenie</p>
        </div>
      </footer>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
